### ISSUE TITLE
Make a Square Cash account

### ISSUE THREAD

**Issue by phivu90** [uxutdallas/uxutdallas#12]

**Comment by chisomekweani** [comment]
I think the best thing to use would be a google wallet account, people can just send us money through there using our ux gmail and it's free as well. It's already set up to our uxutdallas@gmail.com so we won't need to make another account and memorize another email

**Comment by chisomekweani** [comment]
To set up either a square or google wallet account I'll need to actually set it up under someone's name since it requires linking the bank account so I'm going to use mine

**Comment by chisomekweani** [comment]
We already have a square cash account, Logged in and it works
